/**
 * Returns a default value for a quick action.
 */
global class DescribeQuickActionDefaultValue {

  global DescribeQuickActionDefaultValue() {}

  /**
   * Returns the default value of the quick action.
   * @return String
   */
  global String getDefaultValue() {}

  /**
   * Returns the field name of the action.
   * @return String
   */
  global String getField() {}

  global Object clone() {}

}