/**
 * Represents the parameters corresponding to a quick action.
 */
global class DescribeQuickActionParameter {

  global DescribeQuickActionParameter() {}

  global String parametername;

  global String parametertype;

  global String parametervalue;

  global String getParameterName() {}

  global String getParameterType() {}

  global String getParameterValue() {}

  global Object clone() {}

}