/**
 * Contains methods to build an instance of the lxscheduler.SkillRequirement class.
 */
global class SkillRequirementBuilder {

  global SkillRequirementBuilder() {}

  global lxscheduler.SkillRequirement build() {}

  global lxscheduler.SkillRequirementBuilder setSkillId(String skillId) {}

  global lxscheduler.SkillRequirementBuilder setSkillLevel(Double skillLevel) {}

  global Object clone() {}

}