/**
 * Performs rule-based searches for duplicate records. The input is an array of IDs. Each ID specifies records to search for duplicates among. The duplicates are detected based on the active duplicate rules applicable to the object type corresponding to the input IDs.
 */
global class FindDuplicatesByIds {

  global FindDuplicatesByIds() {}

  global static List<Datacloud.FindDuplicatesResult> findDuplicatesByIds(List<Id> ids) {}

  global Object clone() {}

}