/**
 * Contains methods to retrieve and update details that are required to evaluate a learning item.
 */
global class LearningEvaluation {

  global LearningEvaluation() {}

  global Map<String,Object> getDetails() {}

  global String getLearningItemId() {}

  global void setDetails(Map<String,Object> details) {}

  global void setLearningItemId(String learningItemId) {}

  global Object clone() {}

}