/**
 * This class encapsulates the result of a PaginationCursor.fetchPage() call. It contains methods that get the rows for the current page, the start index of the next page, and the number of deleted rows skipped during the fetch operation. It also contains a method that indicates whether the pagination cursor has fetched all available rows in the result set.
 */
global class CursorFetchResult {

  global CursorFetchResult() {}

  global Integer getNextIndex() {}

  global Integer getNumDeletedRecords() {}

  global List<SObject> getRecords() {}

  global Boolean isDone() {}

  global Object clone() {}

}