/**
 * A class that provides context information about a Lightning page. It can be used to help define the values of a picklist in a Lightning component on a Lightning page based on the page’s type and the object with which it’s associated.
 */
global class DesignTimePageContext extends VisualEditor.DynamicPickList {

  global DesignTimePageContext() {}

  global String entityName;

  global String pageType;

  /**
   * Makes a duplicate copy of the VisualEditor.DesignTimePageContext object.
   * @return Object
   */
  global Object clone() {}

}