/**
 * Enables developers to write Apex test classes for connectors used by the connected app provisioning solution. This class simulates provisioning for the associated app.
 */
global class ConnectorTestUtil {

  global ConnectorTestUtil() {}

  /**
   * Creates an instance of a connected app to simulate provisioning.
   * @param connectedAppName Name of the connected app to test for provisioning.
   * @return ConnectedApplication
   */
  global static ConnectedApplication createConnectedApp(String connectedAppName) {}

  global Object clone() {}

}