/**
 * Managed content reference.
 */
global class AbstractManagedContentReference {

  global AbstractManagedContentReference() {}

  /**
   * Unique identifier for the managed content reference.
   */
  global String contentKey;

  /**
   * ID of the managed content reference.
   */
  global String managedContentId;

  /**
   * URL to the single content delivery resource.
   */
  global String resourceUrl;

  global Object clone() {}

}