/**
 * Any diagnostic information that may exist for an executed action link. Diagnostic info is provided only for users who can access the action link.
 */
global class ActionLinkDiagnosticInfo {

  global ActionLinkDiagnosticInfo() {}

  /**
   * Any diagnostic information returned when an action link is executed. Diagnostic information is provided only for users who can access the action link.
   */
  global String diagnosticInfo;

  /**
   * The URL for this action link diagnostic information.
   */
  global String url;

  global Object clone() {}

}