/**
 * Represents an activation contact point field configuration output.
 */
global class ActivationContactPointFieldConfig {

  global ActivationContactPointFieldConfig() {}

  /**
   * ID of the attribute.
   */
  global String attributeId;

  /**
   * Label of the attribute.
   */
  global String attributeLabel;

  /**
   * Name of the attribute.
   */
  global String attributeName;

  /**
   * Preferred name of the attribute.
   */
  global String preferredName;

  global Object clone() {}

}