/**
 * Recommended action information.
 */
global class ActionInfoInputRepresentation {

  global ActionInfoInputRepresentation() {}

  /**
   * Name of the Lightning web component used for dynamically rendering the recommended action.
   */
  global String name;

  /**
   * Parameters required for processing and displaying the recommended action.
   */
  global String parameters;

  global Object clone() {}

}