/**
 * Represents an activation data source configuration output.
 */
global class ActivationDataSourceConfig {

  global ActivationDataSourceConfig() {}

  /**
   * ID of the data source for the activation.
   */
  global String dataSourceId;

  /**
   * Name of the data source for the activation.
   */
  global String dataSourceName;

  /**
   * ID of the market segment activation.
   */
  global String marketSegmentActivationId;

  global Object clone() {}

}