/**
 * Address input representation for a payment method or card payment method.
 */
global class AddressRequest {

  global AddressRequest() {}

  /**
   * Payment method city.
   */
  global String city;

  /**
   * Payment method company name.
   */
  global String companyName;

  /**
   * Payment method country.
   */
  global String country;

  /**
   * Payment method postal code.
   */
  global String postalCode;

  /**
   * Payment method state.
   */
  global String state;

  /**
   * Payment method street.
   */
  global String street;

  global Object clone() {}

}