/**
 * Article item in question and answers suggestions.
 */
global class ArticleItem {

  global ArticleItem() {}

  /**
   * Id of the article.
   */
  global String id;

  /**
   * The rating of the article.
   */
  global Double rating;

  /**
   * Title of the article.
   */
  global String title;

  /**
   * Link URL of the article.
   */
  global String urlLink;

  /**
   * Number of votes given to the article.
   */
  global Integer viewCount;

  global Object clone() {}

}