/**
 * Custom recommendation audience criteria.
 */
global class AudienceCriteria {

  global AudienceCriteria() {}

  /**
   * Specifies the custom recommendation audience criteria type. One of these values: CustomList —A custom list of users makes up the audience. MaxDaysInCommunity —New members make up the audience.
   */
  global ConnectApi.RecommendationAudienceCriteriaType type;

  global Object clone() {}

}