/**
 * Audit Parameters input.
 */
global class AuditParamsRequest {

  global AuditParamsRequest() {}

  /**
   * Email of the client that made the request.
   */
  global String email;

  /**
   * IP address of the client that made the request.
   */
  global String ipAddress;

  /**
   * Mac address of the client that made the request.
   */
  global String macAddress;

  /**
   * Phone number of the client that made the request.
   */
  global String phone;

  global Object clone() {}

}