/**
 * Audience criterion value.
 */
global class AudienceCriterionValueInput {

  global AudienceCriterionValueInput() {}

  /**
   * ID of an audience.
   */
  global String audienceId;

  /**
   * City of a user.
   */
  global String city;

  /**
   * Country of a user.
   */
  global String country;

  /**
   * Domain ID of a user.
   */
  global String domainId;

  /**
   * Field of an object.
   */
  global String entityField;

  /**
   * Type of object.
   */
  global String entityType;

  /**
   * Value of a field.
   */
  global String fieldValue;

  /**
   * Specifies whether the permission is enabled ( true ) or not ( false ) for a user.
   */
  global Boolean isEnabled;

  /**
   * Valid API name of a standard user or custom permission.
   */
  global String permission;

  /**
   * Profile ID of a user.
   */
  global String profileId;

  /**
   * Subdivision of a user.
   */
  global String subdivision;

  global Object clone() {}

}