/**
 * The status of candidate answers on a feed element.
 */
global class CandidateAnswersStatus {

  global CandidateAnswersStatus() {}

  /**
   * Indicates whether candidate answers are available for a question.
   */
  global Boolean hasCandidateAnswers;

  /**
   * Indicates whether any candidate answers are published.
   */
  global Boolean hasCandidateAnswersPublished;

  /**
   * Indicates whether any candidate answers are rated.
   */
  global Boolean hasCandidateAnswersRated;

  global Object clone() {}

}