/**
 * Calculated insight measure.
 */
global class CdpCalculatedInsightMeasure {

  global CdpCalculatedInsightMeasure() {}

  /**
   * API name of the measure.
   */
  global String apiName;

  /**
   * Creation type of the measure.
   */
  global String creationType;

  /**
   * Data source of the measure.
   */
  global ConnectApi.CdpCalculatedInsightDataSource dataSource;

  /**
   * Data type of the measure.
   */
  global String dataType;

  /**
   * Display name of the measure.
   */
  global String displayName;

  /**
   * Field aggregation type of the measure.
   */
  global String fieldAggregationType;

  /**
   * Field role of the measure.
   */
  global String fieldRole;

  /**
   * Formula of the measure.
   */
  global String formula;

  global Object clone() {}

}