/**
 * Calculated insight dimension.
 */
global class CdpCalculatedInsightDimension {

  global CdpCalculatedInsightDimension() {}

  /**
   * API name of the dimension.
   */
  global String apiName;

  /**
   * Creation type of the dimension.
   */
  global String creationType;

  /**
   * Data source of the dimension.
   */
  global ConnectApi.CdpCalculatedInsightDataSource dataSource;

  /**
   * Data type of the dimension.
   */
  global String dataType;

  /**
   * Date granularity of the dimension.
   */
  global String dateGranularity;

  /**
   * Display name of the dimension.
   */
  global String displayName;

  /**
   * Field role of the dimension.
   */
  global String fieldRole;

  /**
   * Formula of the dimension.
   */
  global String formula;

  global Object clone() {}

}