/**
 * Input representation for information when party identification is used in an identity resolution ruleset's match rule criterion.
 */
global class CdpIdentityResolutionMatchCriterionPartyIdentificationInfo {

  global CdpIdentityResolutionMatchCriterionPartyIdentificationInfo() {}

  /**
   * Party identification name.
   */
  global String partyName;

  /**
   * Party identification type.
   */
  global String partyType;

  global Object clone() {}

}