/**
 * Source for an identity resolution default reconciliation rule or field-specific rule using the SourceSequence match method.
 */
global class CdpIdentityResolutionReconciliationSourceOutput {

  global CdpIdentityResolutionReconciliationSourceOutput() {}

  /**
   * If the ruleType for a reconciliation rule is SourceSequence , API name of a source Data Lake Object.
   */
  global String name;

  global Object clone() {}

}