/**
 * Data 360 segment membership table.
 */
global class CdpSegmentMembershipTableOutput {

  global CdpSegmentMembershipTableOutput() {}

  /**
   * Segment membership history table.
   */
  global String historyTable;

  /**
   * Segment membership latest table.
   */
  global String latestTable;

  /**
   * Segment membership profile table.
   */
  global String profileTable;

  global Object clone() {}

}