/**
 * Chatter message page.
 */
global class ChatterMessagePage {

  global ChatterMessagePage() {}

  /**
   * Token identifying the current page.
   */
  global String currentPageToken;

  /**
   * Connect REST API URL identifying the current page.
   */
  global String currentPageUrl;

  /**
   * Messages on the current page.
   */
  global List < ConnectApi.ChatterMessage > messages;

  /**
   * Token identifying the next page, or null if there isn’t a next page.
   */
  global String nextPageToken;

  /**
   * Connect REST API URL identifying the next page, or null if there isn’t a next page.
   */
  global String nextPageUrl;

  global Object clone() {}

}