/**
 * Collection of product summary representations in product search results.
 */
global class CommerceProductSummaryPage {

  global CommerceProductSummaryPage() {}

  /**
   * Number of products per page in search results.
   */
  global Integer pageSize;

  /**
   * Collection of product summaries.
   */
  global List < ConnectApi.CommerceProductSummary > products;

  /**
   * Number of products in search results across all pages.
   */
  global Long total;

  global Object clone() {}

  global Integer getPageSize() {}

  global List<ConnectApi.CommerceProductSummary> getProducts() {}

  global Long getTotal() {}

  global void setPageSize(Integer value) {}

  global void setProducts(List<ConnectApi.CommerceProductSummary> value) {}

  global void setTotal(Long value) {}

}