/**
 * Product selling model information.
 */
global class CommerceProductSellingModel {

  global CommerceProductSellingModel() {}

  /**
   * Indicates whether the product selling model is a subscription product or not.
   */
  global Boolean isSubscriptionProduct;

  global Object clone() {}

  global Boolean getIsSubscriptionProduct() {}

  global void setIsSubscriptionProduct(Boolean value) {}

}