/**
 * The type of repository.
 */
global class ContentHubProviderType {

  global ContentHubProviderType() {}

  /**
   * Localized label of the provider type.
   */
  global String label;

  /**
   * Provider type. One of these values: ContentHubBox ContentHubGDrive ContentHubSharepoint ContentHubSharepointOffice365 ContentHubSharepointOneDrive SimpleUrl
   */
  global String type;

  global Object clone() {}

}