/**
 * Image file details.
 */
global class ContentImageFileDetails {

  global ContentImageFileDetails() {}

  /**
   * Image’s height in pixels.
   */
  global Integer height;

  /**
   * Image’s format.
   */
  global String imageFormat;

  /**
   * Image’s EXIF orientation value, if present.
   */
  global String orientation;

  /**
   * Image’s width in pixels.
   */
  global Integer width;

  global Object clone() {}

}