/**
 * The credit memo that’s being issued as credit. The specified amount from the credit memo balance is issued as payment credit.
 */
global class CreditMemoInputRepresentation {

  global CreditMemoInputRepresentation() {}

  /**
   * The amount of the credit memo balance that’s being issued as credit.
   */
  global Double amount;

  /**
   * The ID of the credit memo.
   */
  global String id;

  global Object clone() {}

}