/**
 * Represents the fields of the Data Model Object (DMO) that contains the JSON records for the data graph.
 */
global class DataGraphValuesDmoField {

  global DataGraphValuesDmoField() {}

  /**
   * List of capabilities for the DMO field.
   */
  global List < Integer > capabilities;

  /**
   * Data type of the DMO field.
   */
  global String dataType;

  /**
   * Developer name of the DMO field.
   */
  global String developerName;

  global Object clone() {}

}