/**
 * Delivery address.
 */
global class DeliveryAddressInputRepresentation {

  global DeliveryAddressInputRepresentation() {}

  /**
   * City in the state for the delivery address.
   */
  global String city;

  /**
   * Country code for the delivery address.
   */
  global String country;

  /**
   * Latitude for the delivery address.
   */
  global Double latitude;

  /**
   * Longitude for the delivery address.
   */
  global Double longitude;

  /**
   * Postal code of the delivery address.
   */
  global String postalCode;

  /**
   * State in the country for the delivery address.
   */
  global String state;

  global Object clone() {}

}