/**
 * Delivery estimation product information.
 */
global class DeliveryEstimationProductInputRepresentation {

  global DeliveryEstimationProductInputRepresentation() {}

  /**
   * Product name.
   */
  global String name;

  /**
   * ID of the product.
   */
  global String productId;

  /**
   * Product quantity.
   */
  global Double quantity;

  /**
   * Product's stock keeping unit (SKU).
   */
  global String stockKeepingUnit;

  global Object clone() {}

}