/**
 * Metadata from a source from a data provider.
 */
global class EinsteinLlmGenerationGenAiSourceReferenceInfo {

  global EinsteinLlmGenerationGenAiSourceReferenceInfo() {}

  /**
   * URL for the source from the data provider.
   */
  global String link;

  /**
   * API name of the source record.
   */
  global String sourceObjectApiName;

  /**
   * ID of the source record.
   */
  global String sourceObjectRecordId;

  global Object clone() {}

}