/**
 * Metadata from an input source that is cited in a generated response.
 */
global class EinsteinLlmGenerationGenAiCitedReference {

  global EinsteinLlmGenerationGenAiCitedReference() {}

  /**
   * URL for the source that is cited in a generated response.
   */
  global String link;

  /**
   * API name of the source record that is cited in a generated response.
   */
  global String sourceObjectApiName;

  /**
   * ID of the source record that is cited in a generated response.
   */
  global String sourceObjectRecordId;

  global Object clone() {}

}