/**
 * Values from a source that is cited in a generated response.
 */
global class EinsteinLlmGenerationGenAiSourceContentInfo {

  global EinsteinLlmGenerationGenAiSourceContentInfo() {}

  /**
   * Text from the source that is cited in the generated response.
   */
  global String content;

  /**
   * API name of the field that is cited in the generated response, such as Opportunity.Amount .
   */
  global String fieldName;

  /**
   * API name of the object that is cited in the generated response, such as Opportunity .
   */
  global String objectName;

  global Object clone() {}

}