/**
 * ID of the asynchronous background operation. This output only includes the operation ID, regardless of whether a call is made to an external payment gateway. It doesn’t include any errors from the operation.
 */
global class EnsureRefundsAsyncOutputRepresentation extends ConnectApi.BaseAsyncOutputRepresentation {

  global EnsureRefundsAsyncOutputRepresentation() {}

  global Object clone() {}

}