/**
 * An extension.
 */
global class Extension {

  global Extension() {}

  /**
   * Alternative representation of the extension.
   */
  global ConnectApi.Alternative alternativeRepresentation;

  /**
   * Attachment ID of the extension.
   */
  global String attachmentId;

  /**
   * ID of the extension.
   */
  global String extensionId;

  /**
   * Payload associated with the extension.
   */
  global String payload;

  /**
   * Payload version that identifies the structure of the payload associated with the extension.
   */
  global String payloadVersion;

  global Object clone() {}

}