/**
 * Default shipping address for an externally managed account.
 */
global class ExternalManagedAccountAddressOutput {

  global ExternalManagedAccountAddressOutput() {}

  /**
   * City of the external managed account record.
   */
  global String city;

  /**
   * Country of the external managed account record.
   */
  global String country;

  /**
   * Geolocation accuracy of the external managed account record.
   */
  global String geolocationAccuracy;

  /**
   * Latitude of the external managed account record.
   */
  global String latitude;

  /**
   * Longitude of the external managed account record.
   */
  global String longitude;

  /**
   * State of the external managed account record.
   */
  global String state;

  /**
   * Street of the external managed account record.
   */
  global String street;

  /**
   * Postal code of the external managed account record.
   */
  global String zip;

  global Object clone() {}

}