/**
 * An extension.
 */
global class ExtensionInput {

  global ExtensionInput() {}

  /**
   * Alternative representation of the extension.
   */
  global ConnectApi.AlternativeInput alternativeRepresentation;

  /**
   * ID of the extension.
   */
  global String extensionId;

  /**
   * Payload associated with the extension.
   */
  global String payload;

  /**
   * Payload version that identifies the structure of the payload associated with the extension.
   */
  global String payloadVersion;

  global Object clone() {}

}