/**
 * Preview and create shifts from a pattern.
 */
global class FieldService {

  global FieldService() {}

  global static ConnectApi.ShiftsFromPattern createShiftsFromPattern(ConnectApi.ShiftsFromPatternInput shiftsFromPatternInput, String shiftPatternId) {}

  global static ConnectApi.ShiftsFromPattern previewShiftsFromPattern(ConnectApi.ShiftsFromPatternInput shiftsFromPatternInput, String shiftPatternId) {}

  global Object clone() {}

}