/**
 * A list of order fulfillment routes with inventory availability information.
 */
global class FindRoutesWithFewestSplitsUsingOCIOutputRepresentation extends ConnectApi.BaseOutputRepresentation {

  global FindRoutesWithFewestSplitsUsingOCIOutputRepresentation() {}

  /**
   * Each element of the list is the response for one element of the input list.
   */
  global List < ConnectApi.FindRoutesWithFewestSplitsWithInventoryOutputRepresentation > results;

  global Object clone() {}

}