/**
 * Marketing integration form.
 */
global class Form {

  global Form() {}

  /**
   * ID of the data extension associated with the marketing integration form.
   */
  global String dataExtensionId;

  /**
   * List of form fields associated with the marketing integration form.
   */
  global ConnectApi.FormFields formFieldsList;

  /**
   * ID of the marketing integration form.
   */
  global String formId;

  /**
   * Name of the marketing integration form.
   */
  global String formName;

  global Object clone() {}

}