/**
 * Describes the Information section of the group. If the group is private, this section is visible only to members.
 */
global class GroupInformation {

  global GroupInformation() {}

  /**
   * The text of the “Information” section of the group.
   */
  global String text;

  /**
   * The title of the “Information” section of the group.
   */
  global String title;

  global Object clone() {}

}