/**
 * A knowledge article version.
 */
global class KnowledgeArticleVersion {

  global KnowledgeArticleVersion() {}

  /**
   * Type of the knowledge article.
   */
  global String articleType;

  /**
   * ID of the knowledge article version.
   */
  global String id;

  /**
   * ID of the corresponding knowledge article.
   */
  global String knowledgeArticleId;

  /**
   * Last published date of the knowledge article.
   */
  global Datetime lastPublishedDate;

  /**
   * Summary of the knowledge article contents.
   */
  global String summary;

  /**
   * Title of the knowledge article.
   */
  global String title;

  /**
   * URL name of the knowledge article.
   */
  global String urlName;

  global Object clone() {}

}