/**
 * Inventory location data used to calculate shipping distance.
 */
global class LocationInputRepresentation {

  global LocationInputRepresentation() {}

  /**
   * The country code of the location.
   */
  global String countryCode;

  /**
   * The identifier of the location.
   */
  global String locationIdentifier;

  /**
   * The postal code of the location.
   */
  global String postalCode;

  global Object clone() {}

}