/**
 * Search information related to the search result.
 */
global class MatchInfo {

  global MatchInfo() {}

  /**
   * Specifies whether search promotion affected the result ( true ) or not ( false ).
   */
  global Boolean isPromoted;

  /**
   * Specifies whether spell correction affected the result ( true ) or not ( false ).
   */
  global Boolean isSpellCorrected;

  global Object clone() {}

}