/**
 * Target that a managed content space folder can be shared with.
 */
global class MCSFolderShareTarget {

  global MCSFolderShareTarget() {}

  /**
   * ID of the share target.
   */
  global String id;

  /**
   * Label of the share target.
   */
  global String label;

  /**
   * Resource URL of the share target that provides target details.
   */
  global String resourceUrl;

  global Object clone() {}

}