/**
 * If a feed element has this capability, users can mute it. Muted feed elements are visible in the muted feed, and invisible in all other feeds that respect mute.
 */
global class MuteCapability extends ConnectApi.FeedElementCapability {

  global MuteCapability() {}

  /**
   * Indicates whether the context user muted the feed element.
   */
  global Boolean isMutedByMe;

  global Object clone() {}

}