/**
 * Navigation menu item page reference.
 */
global class NavigationMenuPageReference {

  global NavigationMenuPageReference() {}

  /**
   * Attributes for the navigation menu item page reference.
   */
  global Map < String , String > attributes;

  /**
   * State for the navigation menu item page reference.
   */
  global Map < String , String > state;

  /**
   * Type for the navigation menu item page reference.
   */
  global String type;

  global Object clone() {}

}