/**
 * Criteria for the new members type of custom recommendation audience.
 */
global class NewUserAudienceCriteriaInput extends ConnectApi.AudienceCriteriaInput {

  global NewUserAudienceCriteriaInput() {}

  /**
   * The maximum number of days since a user became a site member. For example, if you specify 30 , anyone who became a site member in the last 30 days is included in the new members audience.
   */
  global Double value;

  global Object clone() {}

}