/**
 * Order summary verification input.
 */
global class OrderSummaryVerificationInput {

  global OrderSummaryVerificationInput() {}

  /**
   * Guest shopper or registered buyer’s email address.
   */
  global String email;

  /**
   * Guest shopper or registered buyer’s last name.
   */
  global String lastName;

  /**
   * Guest shopper or registered buyer’s phone number.
   */
  global String phoneNumber;

  global Object clone() {}

}