/**
 * Page position information for the object search.
 */
global class PageInfo {

  global PageInfo() {}

  /**
   * Specifies whether the search has more results to return ( true ) or not ( false ).
   */
  global Boolean hasNextPage;

  /**
   * Search page offset position.
   */
  global Integer offset;

  /**
   * Number of results per page.
   */
  global Integer pageSize;

  global Object clone() {}

}