/**
 * Product attribute set data.
 */
global class ProductAttributeSet {

  global ProductAttributeSet() {}

  /**
   * Map of the attributes that are members of the attribute set.
   */
  global Map < String , String > attributes;

  /**
   * Name of the attribute set.
   */
  global String developerName;

  /**
   * ID of the product attribute record that represents the product attribute set.
   */
  global String id;

  global Object clone() {}

}