/**
 * Output representation of the product search image.
 */
global class ProductSearchImageOutputRepresentation {

  global ProductSearchImageOutputRepresentation() {}

  /**
   * Alternate text for the product image.
   */
  global String alternateText;

  /**
   * Media type of the product image.
   */
  global String mediaType;

  /**
   * Sort order of the product image.
   */
  global Integer sortOrder;

  /**
   * Title of the product image.
   */
  global String title;

  /**
   * URL of the product image.
   */
  global String url;

  global Object clone() {}

}