/**
 * Details about a product image.
 */
global class ProductImageOutputRepresentation {

  global ProductImageOutputRepresentation() {}

  /**
   * Alternate text for accessibility.
   */
  global String alternateText;

  /**
   * Media type.
   */
  global String mediaType;

  /**
   * URL of the thumbnail version of the product image.
   */
  global String thumbnailUrl;

  /**
   * Title.
   */
  global String title;

  /**
   * URL of the product image.
   */
  global String url;

  global Object clone() {}

}