/**
 * Output representation of a product details bundle child.
 */
global class ProductBundleChildOutput {

  global ProductBundleChildOutput() {}

  /**
   * Description of the child product.
   */
  global String description;

  /**
   * Child product name.
   */
  global String name;

  /**
   * ProductId of the child product.
   */
  global String productId;

  /**
   * Quantity of the child product per bundle.
   */
  global Double quantity;

  /**
   * Stock Keeping Unit (SKU) of the child product.
   */
  global String stockKeepingUnit;

  global Object clone() {}

}