/**
 * Adjustment group associated with a cart.
 */
global class PromotionCartAdjustmentGroup {

  global PromotionCartAdjustmentGroup() {}

  /**
   * ID of the associated coupon, if applicable.
   */
  global String adjustmentBasisReference;

  /**
   * Description of the adjustment.
   */
  global String adjustmentDescription;

  /**
   * How the price adjustment amount is calculated. Values are: AdjustmentAmount —The adjustment is a fixed amount. AdjustmentPercentage —The adjustment is a percentage.
   */
  global ConnectApi.AdjustmentType adjustmentType;

  /**
   * Price value of the adjustment.
   */
  global String adjustmentValue;

  /**
   * Total amount of the adjustment.
   */
  global String baseAmount;

  /**
   * ID of the cart.
   */
  global String cartId;

  /**
   * ID of the cart adjustment group.
   */
  global String id;

  /**
   * ID of the related promotion.
   */
  global String priceAdjustmentCauseId;

  /**
   * Where in the sequence of adjustments this adjustment was applied.
   */
  global Integer priority;

  global Object clone() {}

}