/**
 * A view of any record in the org, including a custom object record. This object is used if a specialized object, such as User or ChatterGroup, isn’t available for the record type.
 */
global class RecordView extends ConnectApi.AbstractRecordView {

  global RecordView() {}

  /**
   * List of record view sections.
   */
  global List < ConnectApi.RecordViewSection > sections;

  global Object clone() {}

}