/**
 * A list of custom recommendation definitions.
 */
global class RecommendationDefinitionPage {

  global RecommendationDefinitionPage() {}

  /**
   * A list of custom recommendation definitions.
   */
  global List < ConnectApi.RecommendationDefinition > recommendationDefinitions;

  /**
   * URL to the Connect REST API resource for the recommendation definition collection.
   */
  global String url;

  global Object clone() {}

}