/**
 * A related question.
 */
global class RelatedQuestion extends ConnectApi.RelatedFeedPost {

  global RelatedQuestion() {}

  /**
   * Indicates whether the question has a best answer.
   */
  global Boolean hasBestAnswer;

  /**
   * The number of individual views, likes, and comments on a question.
   */
  global ConnectApi.InteractionsCapability interactions;

  global Object clone() {}

}