/**
 * A list of scheduled custom recommendations.
 */
global class ScheduledRecommendationPage {

  global ScheduledRecommendationPage() {}

  /**
   * A list of scheduled custom recommendations.
   */
  global List < ConnectApi.ScheduledRecommendation > scheduledRecommendations;

  /**
   * URL to the Connect REST API resource for the scheduled custom recommendation collection.
   */
  global String url;

  global Object clone() {}

}