/**
 * Represents the address or jurisdiction of the primary business used for calculating tax.
 */
global class TaxJurisdictionResponse {

  global TaxJurisdictionResponse() {}

  /**
   * Country of the tax jurisdiction address.
   */
  global String country;

  /**
   * ID of the tax jurisdiction address.
   */
  global String id;

  /**
   * Level of the tax jurisdiction address.
   */
  global String level;

  /**
   * Name of the tax jurisdiction address.
   */
  global String name;

  /**
   * Region of the tax jurisdiction address.
   */
  global String region;

  /**
   * State-assigned number of the tax jurisdiction address.
   */
  global String stateAssignedNo;

  global Object clone() {}

}