/**
 * Images associated with a topic.
 */
global class TopicImages {

  global TopicImages() {}

  /**
   * URL to a topic’s cover image, which appears on the topic page. Both topics and managed topics can have cover images.
   */
  global String coverImageUrl;

  /**
   * URL to a managed topic’s featured image, which appears wherever you feature it, for example, on your Experience Cloud site home page.
   */
  global String featuredImageUrl;

  global Object clone() {}

}