/**
 * Details of a webstore Meta configuration.
 */
global class WebStoreMetaConfig {

  global WebStoreMetaConfig() {}

  /**
   * External key for Meta Ad Account.
   */
  global String adAccountExtKey;

  /**
   * External key for Meta Business Manager.
   */
  global String businessManagerExtKey;

  /**
   * External key for Meta Catalog.
   */
  global String catalogExtKey;

  /**
   * External key for Meta Commerce Merchant Settings.
   */
  global String commerceMerchantSettingsExtKey;

  /**
   * ID of the Webstore Meta Config entity.
   */
  global String id;

  /**
   * External key for Meta Page.
   */
  global String pageExtKey;

  /**
   * External key for Meta Instagram Profile.
   */
  global String profileExtKey;

  /**
   * External key for Meta Pixel.
   */
  global String trackerExtKey;

  /**
   * ID of the webstore.
   */
  global String webStoreId;

  global Object clone() {}

}