/**
 * List of webstore Meta configurations.
 */
global class WebStoreMetaConfigurations {

  global WebStoreMetaConfigurations() {}

  /**
   * List of webstore Meta configurations.
   */
  global List < ConnectApi.WebStoreMetaConfig > configurations;

  /**
   * Status specifying whether retrieval of webstore Meta configurations was success.
   */
  global ConnectApi.SocialStatusRepresentation status;

  global Object clone() {}

}