/**
 * Page of zone search results.
 */
global class ZoneSearchPage {

  global ZoneSearchPage() {}

  /**
   * Token identifying the current page.
   */
  global String currentPageToken;

  /**
   * Connect REST API URL identifying the current page.
   */
  global String currentPageUrl;

  /**
   * List of search results.
   */
  global List < ConnectApi.ZoneSearchResult > items;

  /**
   * Token identifying the next page, or null if there isn’t a next page.
   */
  global String nextPageToken;

  /**
   * Connect REST API URL identifying the next page, or null if there isn’t a next page.
   */
  global String nextPageUrl;

  global Object clone() {}

}