/**
 * Represents a complex time slot option type. This class is used to provide time option payloads that can be translated to structured content payloads in rich content messages.
 */
global class TimeSlotOption {

  global TimeSlotOption(Datetime startTime, Datetime endTime) {}

  global TimeSlotOption(Datetime startTime, Integer duration) {}

  global Integer duration;

  global Integer durationValue;

  global Datetime endTimeValue;

  global Datetime startTime;

  global Datetime startTimeValue;

  global Object clone() {}

}