/**
 * Contains methods to get locale-specific instances that can be used for comparisons and sorting. Use the getInstance() method to obtain the Collator instance for a given locale and pass the Collator as the Comparator parameter to the list.sort() method.
 */
global class Collator {

  global Collator() {}

  global Integer compare(String source, String target) {}

  global static System.Collator getInstance() {}

  global Object clone() {}

}