/**
 * Provides methods to test an external service's asynchronous callouts, enables sending a mock request, asserts the expected request payload, then triggers the mocked external service’s asynchronous callback response.
 */
global class ExternalServiceTest {

  global ExternalServiceTest() {}

  global Object clone() {}

  global System.HttpResponse sendCallback(System.HttpRequest request) {}

}