/**
 * Use the Http class to initiate an HTTP request and response.
 */
global class Http {

  global Http() {}

  /**
   * Sends an HttpRequest and returns the response.
   * @param request 
   * @return HttpResponse
   */
  global HttpResponse send(HttpRequest request) {}

  /**
   * Returns a string that displays and identifies the object's properties.
   * @return String
   */
  global String toString() {}

  global Object clone() {}

}