/**
 * Contains methods for mathematical operations.
 */
global class Math {

  global Math() {}

  /**
   * Returns the absolute value of the specified Decimal.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal abs(Decimal decimalValue) {}

  /**
   * Returns the absolute value of the specified Decimal.
   * @param doubleValue 
   * @return Double
   */
  global static Double abs(Double doubleValue) {}

  /**
   * Returns the absolute value of the specified Decimal.
   * @param integerValue 
   * @return Integer
   */
  global static Integer abs(Integer integerValue) {}

  /**
   * Returns the absolute value of the specified Decimal.
   * @param longValue 
   * @return Long
   */
  global static Long abs(Long longValue) {}

  /**
   * Returns the arc cosine of an angle, in the range of 0.0 through pi .
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal acos(Decimal decimalAngle) {}

  /**
   * Returns the arc cosine of an angle, in the range of 0.0 through pi .
   * @param doubleAngle 
   * @return Double
   */
  global static Double acos(Double doubleAngle) {}

  /**
   * Returns the arc sine of an angle, in the range of - pi /2 through pi /2.
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal asin(Decimal decimalAngle) {}

  /**
   * Returns the arc sine of an angle, in the range of - pi /2 through pi /2.
   * @param doubleAngle 
   * @return Double
   */
  global static Double asin(Double doubleAngle) {}

  /**
   * Returns the arc tangent of an angle, in the range of - pi /2 through pi /2.
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal atan(Decimal decimalAngle) {}

  /**
   * Returns the arc tangent of an angle, in the range of - pi /2 through pi /2.
   * @param doubleAngle 
   * @return Double
   */
  global static Double atan(Double doubleAngle) {}

  /**
   * Converts rectangular coordinates ( xCoordinate and yCoordinate ) to polar ( r and theta ). This method computes the phase theta by computing an arc tangent of xCoordinate / yCoordinate in the range of - pi to pi .
   * @param xCoordinate 
   * @param yCoordinate 
   * @return Decimal
   */
  global static Decimal atan2(Decimal xCoordinate, Decimal yCoordinate) {}

  /**
   * Converts rectangular coordinates ( xCoordinate and yCoordinate ) to polar ( r and theta ). This method computes the phase theta by computing an arc tangent of xCoordinate / yCoordinate in the range of - pi to pi .
   * @param xCoordinate 
   * @param yCoordinate 
   * @return Double
   */
  global static Double atan2(Double xCoordinate, Double yCoordinate) {}

  /**
   * Returns the cube root of the specified Decimal. The cube root of a negative value is the negative of the cube root of that value's magnitude.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal cbrt(Decimal decimalValue) {}

  /**
   * Returns the cube root of the specified Decimal. The cube root of a negative value is the negative of the cube root of that value's magnitude.
   * @param doubleValue 
   * @return Double
   */
  global static Double cbrt(Double doubleValue) {}

  /**
   * Returns the smallest (closest to negative infinity) Decimal that is not less than the argument and is equal to a mathematical integer.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal ceil(Decimal decimalValue) {}

  /**
   * Returns the smallest (closest to negative infinity) Decimal that is not less than the argument and is equal to a mathematical integer.
   * @param doubleValue 
   * @return Double
   */
  global static Double ceil(Double doubleValue) {}

  /**
   * Returns the trigonometric cosine of the angle specified by decimalAngle .
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal cos(Decimal decimalAngle) {}

  /**
   * Returns the trigonometric cosine of the angle specified by decimalAngle .
   * @param doubleAngle 
   * @return Double
   */
  global static Double cos(Double doubleAngle) {}

  /**
   * Returns the hyperbolic cosine of decimalAngle . The hyperbolic cosine of d is defined to be ( e x + e -x )/2 where e is Euler's number.
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal cosh(Decimal decimalAngle) {}

  /**
   * Returns the hyperbolic cosine of decimalAngle . The hyperbolic cosine of d is defined to be ( e x + e -x )/2 where e is Euler's number.
   * @param doubleAngle 
   * @return Double
   */
  global static Double cosh(Double doubleAngle) {}

  /**
   * Returns Euler's number e raised to the power of the specified Decimal.
   * @param exponentDecimal 
   * @return Decimal
   */
  global static Decimal exp(Decimal exponentDecimal) {}

  /**
   * Returns Euler's number e raised to the power of the specified Decimal.
   * @param exponentDouble 
   * @return Double
   */
  global static Double exp(Double exponentDouble) {}

  /**
   * Returns the largest (closest to positive infinity) Decimal that is not greater than the argument and is equal to a mathematical integer.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal floor(Decimal decimalValue) {}

  /**
   * Returns the largest (closest to positive infinity) Decimal that is not greater than the argument and is equal to a mathematical integer.
   * @param doubleValue 
   * @return Double
   */
  global static Double floor(Double doubleValue) {}

  /**
   * Returns the natural logarithm (base e ) of the specified Decimal.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal log(Decimal decimalValue) {}

  /**
   * Returns the natural logarithm (base e ) of the specified Decimal.
   * @param doubleValue 
   * @return Double
   */
  global static Double log(Double doubleValue) {}

  /**
   * Returns the logarithm (base 10 ) of the specified Decimal.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal log10(Decimal decimalValue) {}

  /**
   * Returns the logarithm (base 10 ) of the specified Decimal.
   * @param doubleValue 
   * @return Double
   */
  global static Double log10(Double doubleValue) {}

  /**
   * Returns the larger of the two specified Decimals.
   * @param decimalValue1 
   * @param decimalValue2 
   * @return Decimal
   */
  global static Decimal max(Decimal decimalValue1, Decimal decimalValue2) {}

  /**
   * Returns the larger of the two specified Decimals.
   * @param doubleValue1 
   * @param doubleValue2 
   * @return Double
   */
  global static Double max(Double doubleValue1, Double doubleValue2) {}

  /**
   * Returns the larger of the two specified Decimals.
   * @param integerValue1 
   * @param integerValue2 
   * @return Integer
   */
  global static Integer max(Integer integerValue1, Integer integerValue2) {}

  /**
   * Returns the larger of the two specified Decimals.
   * @param longValue1 
   * @param longValue2 
   * @return Long
   */
  global static Long max(Long longValue1, Long longValue2) {}

  /**
   * Returns the smaller of the two specified Decimals.
   * @param decimalValue1 
   * @param decimalValue2 
   * @return Decimal
   */
  global static Decimal min(Decimal decimalValue1, Decimal decimalValue2) {}

  /**
   * Returns the smaller of the two specified Decimals.
   * @param doubleValue1 
   * @param doubleValue2 
   * @return Double
   */
  global static Double min(Double doubleValue1, Double doubleValue2) {}

  /**
   * Returns the smaller of the two specified Decimals.
   * @param integerValue1 
   * @param integerValue2 
   * @return Integer
   */
  global static Integer min(Integer integerValue1, Integer integerValue2) {}

  /**
   * Returns the smaller of the two specified Decimals.
   * @param longValue1 
   * @param longValue2 
   * @return Long
   */
  global static Long min(Long longValue1, Long longValue2) {}

  /**
   * Returns the remainder of integerValue1 divided by integerValue2 .
   * @param integerValue1 
   * @param integerValue2 
   * @return Integer
   */
  global static Integer mod(Integer integerValue1, Integer integerValue2) {}

  /**
   * Returns the remainder of integerValue1 divided by integerValue2 .
   * @param longValue1 
   * @param longValue2 
   * @return Long
   */
  global static Long mod(Long longValue1, Long longValue2) {}

  /**
   * Returns the value of the first Double raised to the power of exponent .
   * @param doubleValue 
   * @param exponent 
   * @return Double
   */
  global static Double pow(Double doubleValue, Double exponent) {}

  /**
   * Returns a positive Double that is greater than or equal to 0.0 and less than 1.0.
   * @return Double
   */
  global static Double random() {}

  /**
   * Returns the value that is closest in value to decimalValue and is equal to a mathematical integer.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal rint(Decimal decimalValue) {}

  /**
   * Returns the value that is closest in value to decimalValue and is equal to a mathematical integer.
   * @param doubleValue 
   * @return Double
   */
  global static Double rint(Double doubleValue) {}

  /**
   * Do not use. This method is deprecated as of the Winter '08 release. Instead, use Math.roundToLong . Returns the closest Integer to the specified Double. If the result is less than -2,147,483,648 or greater than 2,147,483,647, Apex generates an error.
   * @param doubleValue 
   * @return Integer
   */
  global static Integer round(Double doubleValue) {}

  /**
   * Do not use. This method is deprecated as of the Winter '08 release. Instead, use Math.roundToLong . Returns the closest Integer to the specified Double. If the result is less than -2,147,483,648 or greater than 2,147,483,647, Apex generates an error.
   * @param decimalValue 
   * @return Integer
   */
  global static Integer round(Decimal decimalValue) {}

  /**
   * Returns the rounded approximation of this Decimal. The number is rounded to zero decimal places using half-even rounding mode, that is, it rounds towards the “nearest neighbor” unless both neighbors are equidistant, in which case, this mode rounds towards the even neighbor.
   * @param decimalValue 
   * @return Long
   */
  global static Long roundToLong(Decimal decimalValue) {}

  /**
   * Returns the rounded approximation of this Decimal. The number is rounded to zero decimal places using half-even rounding mode, that is, it rounds towards the “nearest neighbor” unless both neighbors are equidistant, in which case, this mode rounds towards the even neighbor.
   * @param doubleValue 
   * @return Long
   */
  global static Long roundToLong(Double doubleValue) {}

  /**
   * Returns the signum function of the specified Decimal, which is 0 if decimalValue is 0, 1.0 if decimalValue is greater than 0, -1.0 if decimalValue is less than 0.
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal signum(Decimal decimalValue) {}

  /**
   * Returns the signum function of the specified Decimal, which is 0 if decimalValue is 0, 1.0 if decimalValue is greater than 0, -1.0 if decimalValue is less than 0.
   * @param doubleValue 
   * @return Double
   */
  global static Double signum(Double doubleValue) {}

  /**
   * Returns the trigonometric sine of the angle specified by decimalAngle .
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal sin(Decimal decimalAngle) {}

  /**
   * Returns the trigonometric sine of the angle specified by decimalAngle .
   * @param doubleAngle 
   * @return Double
   */
  global static Double sin(Double doubleAngle) {}

  /**
   * Returns the hyperbolic sine of decimalAngle . The hyperbolic sine of decimalAngle is defined to be ( e x - e -x )/2 where e is Euler's number.
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal sinh(Decimal decimalAngle) {}

  /**
   * Returns the hyperbolic sine of decimalAngle . The hyperbolic sine of decimalAngle is defined to be ( e x - e -x )/2 where e is Euler's number.
   * @param doubleAngle 
   * @return Double
   */
  global static Double sinh(Double doubleAngle) {}

  /**
   * Returns the correctly rounded positive square root of decimalValue .
   * @param decimalValue 
   * @return Decimal
   */
  global static Decimal sqrt(Decimal decimalValue) {}

  /**
   * Returns the correctly rounded positive square root of decimalValue .
   * @param doubleValue 
   * @return Double
   */
  global static Double sqrt(Double doubleValue) {}

  /**
   * Returns the trigonometric tangent of the angle specified by decimalAngle .
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal tan(Decimal decimalAngle) {}

  /**
   * Returns the trigonometric tangent of the angle specified by decimalAngle .
   * @param doubleAngle 
   * @return Double
   */
  global static Double tan(Double doubleAngle) {}

  /**
   * Returns the hyperbolic tangent of decimalAngle . The hyperbolic tangent of decimalAngle is defined to be ( e x - e -x )/( e x + e -x ) where e is Euler's number. In other words, it is equivalent to sinh(x)/cosinh(x) . The absolute value of the exact tanh is always less than 1.
   * @param decimalAngle 
   * @return Decimal
   */
  global static Decimal tanh(Decimal decimalAngle) {}

  /**
   * Returns the hyperbolic tangent of decimalAngle . The hyperbolic tangent of decimalAngle is defined to be ( e x - e -x )/( e x + e -x ) where e is Euler's number. In other words, it is equivalent to sinh(x)/cosinh(x) . The absolute value of the exact tanh is always less than 1.
   * @param doubleAngle 
   * @return Double
   */
  global static Double tanh(Double doubleAngle) {}

  global Object clone() {}

}