/**
 * Contains methods that provide the name, maximum value, and current value of an org limit.
 */
global class OrgLimit {

  global OrgLimit() {}

  /**
   * Returns the maximum allowed limit value.
   * @return Integer
   */
  global Integer getLimit() {}

  /**
   * Returns the limit’s name.
   * @return String
   */
  global String getName() {}

  /**
   * Returns the limit usage value.
   * @return Integer
   */
  global Integer getValue() {}

  global String toString() {}

  global Object clone() {}

}