/**
 * Contains methods to randomly generate a version 4 universally unique identifier (UUID), compare UUIDs, and convert UUID instance to a string.
 */
global class UUID {

  global UUID() {}

  global Boolean equals(Object obj) {}

  global static System.UUID fromString(String str) {}

  global Integer hashCode() {}

  global static System.UUID randomUUID() {}

  global String toString() {}

  global Object clone() {}

}