global class Event {

  global Event() {}

  global String getSubtype() {}

  global String getType() {}

  global override Slack.ActionHandler invoke(Slack.EventParameters parameters, Slack.RequestContext context) {}

  global Object getEvent() {}

  global String getEventId() {}

  global Integer getEventTime() {}

  global String getChannel() {}

  global String getEventTs() {}

  global String getTab() {}

  global String getUser() {}

  global void setChannel(String channel) {}

  global void setEventTs(String eventTs) {}

  global void setTab(String tab) {}

  global void setUser(String user) {}

  global String getTs() {}

  global void setTs(String ts) {}

  global String getName() {}

  global List<String> getNames() {}

  global String getNewName() {}

  global String getOldName() {}

  global String getValue() {}

  global void setName(String name) {}

  global void setNames(List<String> names) {}

  global void setNewName(String newName) {}

  global void setOldName(String oldName) {}

  global void setSubtype(String subtype) {}

  global void setValue(String value) {}

  global Slack.FileChangeEvent.File getFile() {}

  global String getFileId() {}

  global void setFile(Slack.FileChangeEvent.File file) {}

  global void setFileId(String fileId) {}

  global Slack.FileCreatedEvent.File getFile() {}

  global String getUserId() {}

  global void setFile(Slack.FileCreatedEvent.File file) {}

  global void setUserId(String userId) {}

  global List<String> getChannelIds() {}

  global void setChannelIds(List<String> channelIds) {}

  global Slack.FilePublicEvent.File getFile() {}

  global void setFile(Slack.FilePublicEvent.File file) {}

  global String getChannelId() {}

  global Slack.FileSharedEvent.File getFile() {}

  global void setChannelId(String channelId) {}

  global void setFile(Slack.FileSharedEvent.File file) {}

  global Slack.FileUnsharedEvent.File getFile() {}

  global void setFile(Slack.FileUnsharedEvent.File file) {}

  global String getBotId() {}

  global String getChannelType() {}

  global String getText() {}

  global String getThreadTs() {}

  global String getUsername() {}

  global void setBotId(String botId) {}

  global void setChannelType(String channelType) {}

  global void setText(String text) {}

  global void setThreadTs(String threadTs) {}

  global void setUsername(String username) {}

  global Slack.MessageChangedEvent.Message getMessage() {}

  global Slack.MessageChangedEvent.PreviousMessage getPreviousMessage() {}

  global Boolean isHidden() {}

  global void setHidden(Boolean hidden) {}

  global void setMessage(Slack.MessageChangedEvent.Message message) {}

  global void setPreviousMessage(Slack.MessageChangedEvent.PreviousMessage previousMessage) {}

  global Slack.BotProfile getBotProfile() {}

  global String getClientMsgId() {}

  global Boolean getDisplayAsBot() {}

  global List<Slack.File> getFiles() {}

  global Boolean getHidden() {}

  global Boolean getIsLocked() {}

  global String getLastRead() {}

  global String getLatestReply() {}

  global String getParentUserId() {}

  global List<String> getPinnedTo() {}

  global List<Slack.Reaction> getReactions() {}

  global Integer getReplyCount() {}

  global List<String> getReplyUsers() {}

  global Integer getReplyUsersCount() {}

  global String getSourceTeam() {}

  global Boolean getSubscribed() {}

  global String getTeam() {}

  global Boolean getUpload() {}

  global String getUserTeam() {}

  global List<String> getXFiles() {}

  global Boolean isStarred() {}

  global void setBotProfile(Slack.BotProfile botProfile) {}

  global void setClientMsgId(String clientMsgId) {}

  global void setDisplayAsBot(Boolean displayAsBot) {}

  global void setFiles(List<Slack.File> files) {}

  global void setIsLocked(Boolean isLocked) {}

  global void setLastRead(String lastRead) {}

  global void setLatestReply(String latestReply) {}

  global void setParentUserId(String parentUserId) {}

  global void setPinnedTo(List<String> pinnedTo) {}

  global void setReactions(List<Slack.Reaction> reactions) {}

  global void setReplyCount(Integer replyCount) {}

  global void setReplyUsers(List<String> replyUsers) {}

  global void setReplyUsersCount(Integer replyUsersCount) {}

  global void setSourceTeam(String sourceTeam) {}

  global void setStarred(Boolean starred) {}

  global void setSubscribed(Boolean subscribed) {}

  global void setTeam(String team) {}

  global void setUpload(Boolean upload) {}

  global void setUserTeam(String userTeam) {}

  global void setXFiles(List<String> xFiles) {}

  global String getDeletedTs() {}

  global Slack.MessageDeletedEvent.Message getPreviousMessage() {}

  global void setDeletedTs(String deletedTs) {}

  global void setPreviousMessage(Slack.MessageDeletedEvent.Message previousMessage) {}

  global void setTs(String user) {}

  global Slack.MessageEvent.Edited getEdited() {}

  global void setEdited(Slack.MessageEvent.Edited edited) {}

  global String getTopic() {}

  global void setTopic(String topic) {}

  global Slack.MessageRepliedEvent.Message getMessage() {}

  global void setMessage(Slack.MessageRepliedEvent.Message message) {}

  global Slack.PinAddedEvent.Item getItem() {}

  global String getItemUser() {}

  global Integer getPinCount() {}

  global Slack.PinAddedEvent.PinnedInfo getPinnedInfo() {}

  global void setItem(Slack.PinAddedEvent.Item item) {}

  global void setItemUser(String itemUser) {}

  global void setPinCount(Integer pinCount) {}

  global void setPinnedInfo(Slack.PinAddedEvent.PinnedInfo pinnedInfo) {}

  global Slack.FileComment getComment() {}

  global Integer getCreated() {}

  global String getCreatedBy() {}

  global Slack.File getFile() {}

  global Slack.PinAddedEvent.Message getMessage() {}

  global void setComment(Slack.FileComment comment) {}

  global void setCreated(Integer created) {}

  global void setCreatedBy(String createdBy) {}

  global void setFile(Slack.File file) {}

  global void setMessage(Slack.PinAddedEvent.Message message) {}

  global void setType(String type) {}

  global String getAppId() {}

  global String getPermalink() {}

  global void setPermalink(String permalink) {}

  global String getPinnedBy() {}

  global Long getPinnedTs() {}

  global void setPinnedBy(String pinnedBy) {}

  global void setPinnedTs(Long pinnedTs) {}

  global Slack.PinRemovedEvent.Item getItem() {}

  global Slack.PinRemovedEvent.PinnedInfo getPinnedInfo() {}

  global Boolean isHasPins() {}

  global void setHasPins(Boolean hasPins) {}

  global void setItem(Slack.PinRemovedEvent.Item item) {}

  global Slack.PinRemovedEvent.Message getMessage() {}

  global void setMessage(Slack.PinRemovedEvent.Message message) {}

  global void setAppId(String appId) {}

  global Slack.ReactionAddedEvent.Item getItem() {}

  global String getReaction() {}

  global void setItem(Slack.ReactionAddedEvent.Item item) {}

  global void setReaction(String reaction) {}

  global String getFile() {}

  global String getFileComment() {}

  global void setFile(String file) {}

  global void setFileComment(String fileComment) {}

  global Slack.ReactionRemovedEvent.Item getItem() {}

  global void setItem(Slack.ReactionRemovedEvent.Item item) {}

  global Slack.StarAddedEvent.Item getItem() {}

  global void setItem(Slack.StarAddedEvent.Item item) {}

  global Long getDateCreate() {}

  global Slack.StarAddedEvent.Message getMessage() {}

  global void setDateCreate(Long dateCreate) {}

  global void setMessage(Slack.StarAddedEvent.Message message) {}

  global Slack.StarAddedEvent.Edited getEdited() {}

  global void setEdited(Slack.StarAddedEvent.Edited edited) {}

  global void setStarred(Boolean isStarred) {}

  global Slack.StarRemovedEvent.Item getItem() {}

  global void setItem(Slack.StarRemovedEvent.Item item) {}

  global Slack.StarRemovedEvent.Message getMessage() {}

  global void setMessage(Slack.StarRemovedEvent.Message message) {}

  global Slack.StarRemovedEvent.Edited getEdited() {}

  global void setEdited(Slack.StarRemovedEvent.Edited edited) {}

  global Slack.SubteamCreatedEvent.Subteam getSubteam() {}

  global void setSubteam(Slack.SubteamCreatedEvent.Subteam subteam) {}

  global List<String> getChannels() {}

  global void setChannels(List<String> channels) {}

  global void setGroups(List<String> groups) {}

  global String getAutoType() {}

  global Integer getChannelCount() {}

  global Integer getDateCreate() {}

  global Integer getDateDelete() {}

  global Integer getDateUpdate() {}

  global String getDeletedBy() {}

  global String getDescription() {}

  global String getEnterpriseSubteamId() {}

  global String getHandle() {}

  global String getId() {}

  global Slack.SubteamCreatedEvent.Prefs getPrefs() {}

  global String getTeamId() {}

  global String getUpdatedBy() {}

  global Integer getUserCount() {}

  global List<String> getUsers() {}

  global Boolean isAutoProvision() {}

  global Boolean isExternal() {}

  global Boolean isSubteam() {}

  global Boolean isUsergroup() {}

  global void setAutoProvision(Boolean autoProvision) {}

  global void setAutoType(String autoType) {}

  global void setChannelCount(Integer channelCount) {}

  global void setDateCreate(Integer dateCreate) {}

  global void setDateDelete(Integer dateDelete) {}

  global void setDateUpdate(Integer dateUpdate) {}

  global void setDeletedBy(String deletedBy) {}

  global void setDescription(String description) {}

  global void setEnterpriseSubteamId(String enterpriseSubteamId) {}

  global void setExternal(Boolean external) {}

  global void setHandle(String handle) {}

  global void setId(String id) {}

  global void setPrefs(Slack.SubteamCreatedEvent.Prefs prefs) {}

  global void setSubteam(Boolean isSubteam) {}

  global void setTeamId(String teamId) {}

  global void setUpdatedBy(String updatedBy) {}

  global void setUserCount(Integer userCount) {}

  global void setUsergroup(Boolean isUsergroup) {}

  global void setUsers(List<String> users) {}

  global List<String> getAddedUsers() {}

  global Integer getAddedUsersCount() {}

  global Integer getDatePreviousUpdate() {}

  global List<String> getRemovedUsers() {}

  global Integer getRemovedUsersCount() {}

  global String getSubteamId() {}

  global void setAddedUsers(List<String> addedUsers) {}

  global void setAddedUsersCount(Integer addedUsersCount) {}

  global void setDatePreviousUpdate(Integer datePreviousUpdate) {}

  global void setRemovedUsers(List<String> removedUsers) {}

  global void setRemovedUsersCount(Integer removedUsersCount) {}

  global void setSubteamId(String subteamId) {}

  global Slack.SubteamUpdatedEvent.Subteam getSubteam() {}

  global void setSubteam(Slack.SubteamUpdatedEvent.Subteam subteam) {}

  global List<String> getGroups() {}

  global Slack.SubteamUpdatedEvent.Prefs getPrefs() {}

  global void setExternal(Boolean isExternal) {}

  global void setPrefs(Slack.SubteamUpdatedEvent.Prefs prefs) {}

  global List<String> getTeamIds() {}

  global void setTeamIds(List<String> teamIds) {}

  global String getDomain() {}

  global String getUrl() {}

  global void setDomain(String domain) {}

  global void setUrl(String url) {}

  global Slack.User getUser() {}

  global void setUser(Slack.User user) {}

  global Slack.TokensRevokedEvent.Tokens getTokens() {}

  global void setTokens(Slack.TokensRevokedEvent.Tokens tokens) {}

  global List<String> getBot() {}

  global List<String> getOauth() {}

  global void setBot(List<String> bot) {}

  global void setOauth(List<String> oauth) {}

  global Integer getCacheTs() {}

  global void setCacheTs(Integer cacheTs) {}

  global List<String> getScopes() {}

  global String getTriggerId() {}

  global void setScopes(List<String> scopes) {}

  global void setTriggerId(String triggerId) {}

  global Object clone() {}

}