global class Modals {

  global Modals() {}

  global Slack.ModalView call() {}

  global static Slack.ModalView.Builder builder() {}

  global Slack.ModalView build() {}

  global Slack.ModalView.Builder clearOnClose(Boolean clearOnClose) {}

  global Slack.ModalView.Builder externalId(String externalId) {}

  global Slack.ModalView.Builder viewReference(Slack.ViewReference viewReference) {}

  global Object clone() {}

}