global class ResponseMetadata {

  global ResponseMetadata() {}

  global List<String> getMessages() {}

  global String getNextCursor() {}

  global Slack.ResponseMetadata getResponseMetadata() {}

  global List<String> getWarnings() {}

  global void setMessages(List<String> messages) {}

  global void setNextCursor(String nextCursor) {}

  global void setResponseMetadata(Slack.ResponseMetadata responseMetadata) {}

  global void setWarnings(List<String> warnings) {}

  global Object clone() {}

}