/**
 * The class contains the response details of the alternative payment method.
 */
global class AlternativePaymentMethodResponse {

  global AlternativePaymentMethodResponse() {}

  global void setAccountId(Id accountId) {}

  global void setComments(String comments) {}

  global void setEmail(String email) {}

  global void setGatewayToken(String gatewayToken) {}

  global void setGatewayTokenDetails(String gatewayTokenDetails) {}

  global void setName(String name) {}

  global Object clone() {}

}