/**
 * Contains the data for a cell in the report, including the display label and value.
 */
global class ReportDataCell {

  global ReportDataCell() {}

  /**
   * Returns the localized display name of the value of a specified cell in the report.
   * @return String
   */
  global String getLabel() {}

  /**
   * Returns the value of a specified cell of a detail row of a report.
   * @return Object
   */
  global Object getValue() {}

  global Object clone() {}

}