/**
 * Contains report type metadata, which gives you information about the fields that are available in each section of the report type, plus filter information for those fields.
 */
global class ReportTypeMetadata {

  global ReportTypeMetadata() {}

  /**
   * Returns all fields in the report type. The fields are organized by section.
   * @return LIST<Reports.ReportTypeColumnCategory>
   */
  global LIST<Reports.ReportTypeColumnCategory> getCategories() {}

  /**
   * Returns the default division and a list of all possible divisions that can be applied to this type of report.
   * @return Reports.ReportDivisionInfo
   */
  global Reports.ReportDivisionInfo getDivisionInfo() {}

  /**
   * Returns information about the scopes that can be applied to this type of report.
   * @return Reports.ReportScopeInfo
   */
  global Reports.ReportScopeInfo getScopeInfo() {}

  /**
   * Returns information about the standard date filter groupings that can be applied to this type of report. Standard date filter groupings include Calendar Year, Calendar Quarter, Calendar Month, Calendar Week, Fiscal Year, Fiscal Quarter, Day and a custom value based on a user-defined date range.
   * @return List<Reports.StandardDateFilterDurationGroup>
   */
  global List<Reports.StandardDateFilterDurationGroup> getStandardDateFilterDurationGroups() {}

  /**
   * Returns information about standard date filters that can be applied to this type of report.
   * @return Map<String,Reports.StandardFilterInfo>
   */
  global Map<String,Reports.StandardFilterInfo> getStandardFilterInfos() {}

  global Object clone() {}

}